config/routes.rb
FirstRide::Application.routes.draw do
  resources :cars

  root :to => "cars#index"

end

app/models/car.rb
class Car < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/cars_controller.rb
class CarsController < InheritedResources::Base
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/_form.html.haml
= form_for @car do |f|
  -if @car.errors.any?
    #errorExplanation
      %h2= "#{pluralize(@car.errors.count, "error")} prohibited this car from being saved:"
      %ul
        - @car.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :description
    = f.text_area :description
  .actions
    = f.submit 'Save'

app/views/cars/edit.html.haml
%h1 Editing car

= render 'form'

= link_to 'Show', @car
\|
= link_to 'Back', cars_path

app/views/cars/index.html.haml
%h1 Listing cars

%table
  %tr
    %th Title
    %th Description
    %th
    %th
    %th

  - @cars.each do |car|
    %tr
      %td= car.title
      %td= car.description
      %td= link_to 'Show', car
      %td= link_to 'Edit', edit_car_path(car)
      %td= link_to 'Destroy', car, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New car', new_car_path

app/views/cars/new.html.haml
%h1 New car

= render 'form'

= link_to 'Back', cars_path

app/views/cars/show.html.haml
%p
  %b Title:
  = @car.title
%p
  %b Description:
  = @car.description

= link_to 'Edit', edit_car_path(@car)
\|
= link_to 'Back', cars_path

app/views/layouts/application.html.haml
!!!
%html
%head
%title First ride
= stylesheet_link_tag :all
= javascript_include_tag :defaults
= javascript_include_tag "application"
= csrf_meta_tag
%body
= yield